[package]
name = "archphene-packages"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
archphene-process = { path = "../archphene-process" }
flate2 = "1.1.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
tar = { version = "0.4.44", default-features = false }
