package org.archphene.app.launcher

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class LauncherApkAssemblerTest {
    @Test
    fun acceptsOnlyCanonicalImplementedCapabilityContracts() {
        assertTrue(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_V10,
            ),
        )
        assertTrue(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_PRINTING_V10,
            ),
        )
        assertTrue(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_AUDIO_V10,
            ),
        )
        assertTrue(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_AUDIO_PRINTING_V10,
            ),
        )
        assertTrue(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_AUDIO_INPUT_V10,
            ),
        )
        assertTrue(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_AUDIO_INPUT_PRINTING_V10,
            ),
        )
        assertTrue(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_SECRETS_V10,
            ),
        )
        assertTrue(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_AUDIO_INPUT_PRINTING_SECRETS_V10,
            ),
        )
        assertFalse(
            LauncherApkAssembler.validCapabilities(
                "${LauncherApkAssembler.CAPABILITIES_V10},accessibility",
            ),
        )
        assertFalse(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_V4,
            ),
        )
        assertTrue(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_CAMERA_V10,
            ),
        )
        assertTrue(
            LauncherApkAssembler.validCapabilities(
                LauncherApkAssembler.CAPABILITIES_AUDIO_INPUT_PRINTING_SECRETS_CAMERA_V10,
            ),
        )
        assertTrue(
            LauncherApkAssembler.hasCameraCapability(
                LauncherApkAssembler.CAPABILITIES_CAMERA_V10,
            ),
        )
        assertFalse(
            LauncherApkAssembler.hasCameraCapability(
                LauncherApkAssembler.CAPABILITIES_SECRETS_V10,
            ),
        )
        assertTrue(
            LauncherApkAssembler.validMetadataCapabilities(
                "c:${LauncherApkAssembler.CAPABILITIES_PRINTING_V10}",
            ),
        )
        assertFalse(
            LauncherApkAssembler.validMetadataCapabilities(
                LauncherApkAssembler.CAPABILITIES_PRINTING_V10,
            ),
        )
    }
}
