[package]
name = "archphene-android"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
archphene-core = { path = "../archphene-core" }
archphene-builder = { path = "../archphene-builder" }
archphene-jobs = { path = "../archphene-jobs" }
archphene-launcher = { path = "../archphene-launcher" }
archphene-packages = { path = "../archphene-packages" }
archphene-process = { path = "../archphene-process" }
archphene-runtime = { path = "../archphene-runtime" }
archphene-storage = { path = "../archphene-storage" }
sha2 = "0.10.9"

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.21.1", default-features = false }
rustix = { version = "1.1.4", features = ["fs"] }
