#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/android-build.sh"
skip_install=false; descriptor_path=; serial=
while (($#)); do case "$1" in --skip-install) skip_install=true; shift;; --descriptor-path) descriptor_path="${2:?}"; shift 2;; --serial) serial="${2:?}"; shift 2;; -h|--help) echo "usage: $0 [--skip-install] [--descriptor-path PATH] [--serial SERIAL]"; exit 0;; *) archphene_die "unknown argument: $1";; esac; done
archphene_require_command jq; archphene_require_command podman; archphene_init_android_build
app="$ARCHPHENE_ROOT/prototypes/mousepad-android-app"; out="$app/out"; descriptor_path="${descriptor_path:-$app/archphene-app.json}"; archphene_require_file "$descriptor_path"
schema="$(jq -r .schema "$descriptor_path")"; package="$(jq -r .android.package "$descriptor_path")"; [[ "$schema" == org.archphene.app.v1 ]] || archphene_die "unsupported Archphene app descriptor schema: $schema"; [[ "$package" == org.archphene.linux.mousepad ]] || archphene_die 'this Mousepad wrapper requires package org.archphene.linux.mousepad'
version_name="$(jq -r .android.versionName "$descriptor_path")"; version_code="$(jq -r .android.versionCode "$descriptor_path")"; label="$(jq -r .android.label "$descriptor_path")"; metadata_url="$(jq -r .source.metadataUrl "$descriptor_path")"; linux_abi="$(jq -r .runtime.linuxAbi "$descriptor_path")"; payload_rel="$(jq -r .payload.apkLibrary "$descriptor_path")"; payload_hash="$(jq -r .payload.sha256 "$descriptor_path" | tr '[:upper:]' '[:lower:]')"
manifest="$app/AndroidManifest.xml"; python3 - "$manifest" <<'PY'
import sys,xml.etree.ElementTree as ET
r=ET.parse(sys.argv[1]).getroot(); ns='{http://schemas.android.com/apk/res/android}'; found=[x for x in r.findall('./application/provider') if x.get(ns+'name')=='org.archphene.bridge.LinuxHomeBrokerProvider']; raise SystemExit(0 if len(found)==1 else f'Mousepad manifest must declare exactly one LinuxHomeBrokerProvider; found {len(found)}')
PY
for expected in "$package" "$label" "$version_name" "$metadata_url" "$linux_abi"; do grep -Fq "$expected" "$manifest" || archphene_die "Android manifest does not match descriptor value: $expected"; done
[[ "$(archphene_sha256_file "$app/$payload_rel")" == "$payload_hash" ]] || archphene_die 'packaged Linux entrypoint does not match descriptor SHA-256'
lib="$app/lib/x86_64"; mkdir -p "$lib"; helper="$ARCHPHENE_ROOT/tooling/build/wrapper-templates/qt/stage/lib/x86_64"
for file in libarchphene_dbus_daemon.so libarchphene_portal_service.so libarchphene_xdg_open.so; do archphene_require_file "$helper/$file"; cp "$helper/$file" "$lib/$file"; done
"$ARCHPHENE_SCRIPTS_DIR/build-native-compositor-podman.sh" --architecture x86_64 --release; cp "$ARCHPHENE_ROOT/native/archphene-compositor/target/x86_64-linux-android/release/libarchphene_compositor.so" "$lib/"
svg_pkg="$ARCHPHENE_ROOT/tooling/sources/librsvg-noglycin/librsvg-noglycin-2.62.3-1-x86_64.pkg.tar.zst"; pixbuf_pkg="$ARCHPHENE_ROOT/tooling/sources/gdk-pixbuf2-noglycin/gdk-pixbuf2-noglycin-2.44.6-2-x86_64.pkg.tar.zst"; archphene_require_file "$svg_pkg"; archphene_require_file "$pixbuf_pkg"
stage="$ARCHPHENE_ROOT/tooling/build/mousepad-svg-loader"; rm -rf "$stage"; mkdir -p "$stage"; tar -xf "$svg_pkg" -C "$stage" usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader_svg.so usr/lib/librsvg-2.so.2.62.3; tar -xf "$pixbuf_pkg" -C "$stage" usr/lib/libgdk_pixbuf-2.0.so.0.4400.6
cp "$stage/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader_svg.so" "$lib/libarchphene_pixbufloader_svg.so"; rm -f "$lib"/libgdk_pixbuf-2.0.so* "$lib"/libglycin* "$lib/libarchphene_glycin_svg.so"
for name in libgdk_pixbuf-2.0.so libgdk_pixbuf-2.0.so.0 libgdk_pixbuf-2.0.so.0.4400.6; do cp "$stage/usr/lib/libgdk_pixbuf-2.0.so.0.4400.6" "$lib/$name"; done
for name in librsvg-2.so librsvg-2.so.2 librsvg-2.so.2.62.3; do cp "$stage/usr/lib/librsvg-2.so.2.62.3" "$lib/$name"; done
runtime="$ARCHPHENE_ROOT/tooling/downloads/arch-curated-mousepad-x86_64/runtime-root"; data="$runtime/usr/share"; gtk_pkg="$(find "$ARCHPHENE_ROOT/tooling/downloads/arch-curated-mousepad-x86_64/packages" -maxdepth 1 -type f -name 'gtk3-*.pkg.tar.zst' -print -quit)"; [[ -n "$gtk_pkg" ]] || archphene_die 'resolved Arch gtk3 package is missing'
gtk_stage="$ARCHPHENE_ROOT/tooling/build/mousepad-gtk-module"; rm -rf "$gtk_stage"; mkdir -p "$gtk_stage"; tar -xf "$gtk_pkg" -C "$gtk_stage" usr/lib/gtk-3.0/3.0.0/immodules/im-wayland.so; cp "$gtk_stage/usr/lib/gtk-3.0/3.0.0/immodules/im-wayland.so" "$lib/libarchphene_im_wayland.so"
archphene_require_directory "$data"; xkb="$data/xkeyboard-config-2"; preserved="$ARCHPHENE_ROOT/tooling/downloads/arch-curated-mousepad-x86_64/runtime-root-ntfs-symlinks/usr/share/xkeyboard-config-2"; if [[ ! -d "$xkb" ]]; then archphene_require_directory "$preserved"; cp -a "$preserved" "$xkb"; fi
for pair in 'xorg evdev' 'xorg.lst evdev.lst' 'xorg.xml evdev.xml'; do read -r alias target <<<"$pair"; if [[ ! -s "$xkb/rules/$alias" || -L "$xkb/rules/$alias" ]]; then rm -f "$xkb/rules/$alias"; cp "$xkb/rules/$target" "$xkb/rules/$alias"; fi; done
schemas="$data/glib-2.0/schemas"; schema_cache="$schemas/gschemas.compiled"; if [[ ! -f "$schema_cache" ]] || find "$schemas" -maxdepth 1 -name '*.xml' -newer "$schema_cache" -print -quit | grep -q .; then podman run --rm -v "$ARCHPHENE_ROOT:/workspace" -w /workspace localhost/archphene-android-native:ndk29-rust1.88 glib-compile-schemas /workspace/tooling/downloads/arch-curated-mousepad-x86_64/runtime-root/usr/share/glib-2.0/schemas; fi; archphene_require_file "$schema_cache"
mime="$data/mime"; mime_cache="$mime/mime.cache"; mime_source="$mime/packages/freedesktop.org.xml"; if [[ ! -f "$mime_cache" || "$mime_source" -nt "$mime_cache" ]]; then podman run --rm -v "$ARCHPHENE_ROOT:/workspace" -w /workspace localhost/archphene-android-native:ndk29-rust1.88 update-mime-database /workspace/tooling/downloads/arch-curated-mousepad-x86_64/runtime-root/usr/share/mime; fi; archphene_require_file "$mime_cache"
data_asset="$app/assets/mousepad-data.zip"; if [[ ! -f "$data_asset" || "$schema_cache" -nt "$data_asset" || "$mime_cache" -nt "$data_asset" ]]; then (cd "$runtime" && jar cf "$data_asset" usr/share); fi
gconv_root="$ARCHPHENE_ROOT/tooling/downloads/arch-curated-kcalc-x86_64/runtime-root"; archphene_require_directory "$gconv_root/usr/lib/gconv"; [[ -f "$app/assets/glibc-gconv.zip" ]] || (cd "$gconv_root" && jar cf "$app/assets/glibc-gconv.zip" usr/lib/gconv)
clang="$ARCHPHENE_NDK_BIN/x86_64-linux-android35-clang"; include="$app/wayland-include"; for item in frame_client shm_frame_client wayland_shm_client wayland_evented_client wayland_xdg_client; do "$clang" -fPIE -pie -O2 -Wall -Wextra -o "$lib/libarchphene_${item}.so" "$app/archphene_${item}.c"; done
"$clang" -fPIE -pie -O2 -Wall -Wextra -I "$include" -L "$lib" -Wl,--allow-shlib-undefined -o "$lib/libarchphene_wayland_api_client.so" "$app/archphene_wayland_api_client.c" -l:libwayland-client.so.0
"$clang" -shared -fPIC -O2 -Wall -Wextra -I "$include" -Wl,-soname,libarchphene_wayland_client_android.so -o "$lib/libarchphene_wayland_client_android.so" "$app/archphene_wayland_client_android.c"
for suffix in '' _render _xdg; do "$clang" -fPIE -pie -O2 -Wall -Wextra -I "$include" -L "$lib" -Wl,--allow-shlib-undefined -o "$lib/libarchphene_wayland_android_api${suffix}_client.so" "$app/archphene_wayland_api${suffix}_client.c" -l:libarchphene_wayland_client_android.so; done
podman run --rm -v "$ARCHPHENE_ROOT:/workspace" -w /workspace -e GOOS=linux -e GOARCH=amd64 -e CGO_ENABLED=0 -e GO111MODULE=off docker.io/library/golang:1.24 go build -trimpath -ldflags '-s -w' -o /workspace/prototypes/mousepad-android-app/lib/x86_64/libarchphene_syscall_probe.so /workspace/prototypes/linux-payloads/syscall-probe/main.go
key="$(archphene_ensure_named_debug_keystore archpheneos-mousepad-debug.keystore 'CN=Mousepad,O=ArchpheneOS,C=US')"; archphene_package_android_app "$app" "$out" "$manifest" x86_64 "$version_code" "$version_name" "$key" archpheneos-mousepad.apk
if [[ "$skip_install" == false ]]; then [[ -n "$serial" ]] || archphene_die '--serial is required when installing'; archphene_init_adb "$serial"; archphene_adb_run install --no-incremental -r "$out/archpheneos-mousepad.apk"; archphene_adb_run shell am start -n "$package/$package.MainActivity"; fi
archphene_note "Mousepad wrapper built: $out/archpheneos-mousepad.apk"
