#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"
serial=emulator-5554; android_sdk=; output_json=; output_markdown=; packages=(); labels=()
while (($#)); do case "$1" in --serial) serial="${2:?}"; shift 2;; --android-sdk) android_sdk="${2:?}"; shift 2;; --package) packages+=("${2:?}"); shift 2;; --label) labels+=("${2:?}"); shift 2;; --output-json) output_json="${2:?}"; shift 2;; --output-markdown) output_markdown="${2:?}"; shift 2;; -h|--help) echo "usage: $0 [--serial SERIAL] [--package ID] [--label ID=TEXT] [--output-json PATH] [--output-markdown PATH]"; exit 0;; *) archphene_die "unknown argument: $1";; esac; done
[[ -z "$android_sdk" ]] || export ANDROID_SDK_ROOT="$android_sdk"; archphene_init_adb "$serial"; archphene_adb_run get-state >/dev/null
tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
installed="$(archphene_adb_run shell pm list packages | sed 's/^package://;s/\r$//')"
if ((${#packages[@]}==0)); then packages=(org.archpheneos.manager org.archpheneos.terminal); while IFS= read -r p; do [[ "$p" =~ ^org\.archphene\.linux\.p[0-9a-f]{32}$ ]] && packages+=("$p"); done <<<"$installed"; for p in org.archphene.linux.kcalc org.archphene.linux.mousepad; do grep -Fxq "$p" <<<"$installed" && packages+=("$p"); done; fi
adb_root=false; [[ "$(archphene_adb_run shell id -u 2>/dev/null | tr -d '\r')" == 0 ]] && adb_root=true
private() { local package="$1"; shift; if archphene_adb_run shell run-as "$package" "$@" 2>/dev/null; then return; fi; [[ "$adb_root" == true ]] || return 1; local mapped=() value; for value in "$@"; do case "$value" in .) mapped+=("/data/user/0/$package");; files|files/*|cache|cache/*|code_cache|code_cache/*) mapped+=("/data/user/0/$package/$value");; *) mapped+=("$value");; esac; done; archphene_adb_run shell "${mapped[@]}"; }
kib() { local value; value="$($@ 2>/dev/null | head -n1 | awk '{print $1}')" || true; [[ "$value" =~ ^[0-9]+$ ]] && echo "$value" || echo null; }
for package in "${packages[@]}"; do grep -Fxq "$package" <<<"$installed" || continue; dump="$(archphene_adb_run shell dumpsys package "$package")"; version_code="$(sed -n 's/.*versionCode=\([0-9]*\).*/\1/p' <<<"$dump" | head -n1)"; version_name="$(sed -n 's/.*versionName=\([^[:space:]]*\).*/\1/p' <<<"$dump" | head -n1)"; abi="$(sed -n 's/.*primaryCpuAbi=\([^[:space:]]*\).*/\1/p' <<<"$dump" | head -n1)"; kind=generated-wrapper; [[ "$package" == org.archpheneos.manager ]] && kind=manager; [[ "$package" == org.archpheneos.terminal ]] && kind=terminal
  accessible=false; private "$package" pwd >/dev/null 2>&1 && accessible=true; data=null; files=null; cache=null; code_cache=null; if [[ "$accessible" == true ]]; then data="$(kib private "$package" du -sk .)"; files="$(kib private "$package" du -sk files)"; cache="$(kib private "$package" du -sk cache)"; code_cache="$(kib private "$package" du -sk code_cache)"; fi
  apk_bytes=0; code_kib=null; mapfile -t paths < <(archphene_adb_run shell pm path "$package" | sed 's/^package://;s/\r$//'); if ((${#paths[@]})); then code_kib="$(kib archphene_adb_run shell du -sk "${paths[0]%/*}")"; for path in "${paths[@]}"; do size="$(archphene_adb_run shell stat -c %s "$path" 2>/dev/null | tr -d '\r')"; [[ "$size" =~ ^[0-9]+$ ]] || { apk_bytes=null; break; }; apk_bytes=$((apk_bytes+size)); done; else apk_bytes=null; fi
  jq -nc --arg package "$package" --arg kind "$kind" --arg versionName "$version_name" --arg abi "$abi" --argjson versionCode "${version_code:-null}" --argjson apkBytes "$apk_bytes" --argjson codeKiB "$code_kib" --argjson dataKiB "$data" --argjson filesKiB "$files" --argjson cacheKiB "$cache" --argjson codeCacheKiB "$code_cache" --argjson accessible "$accessible" '{Package:$package,Kind:$kind,VersionName:$versionName,VersionCode:$versionCode,Abi:$abi,ApkBytes:$apkBytes,CodeKiB:$codeKiB,DataKiB:$dataKiB,FilesKiB:$filesKiB,CacheKiB:$cacheKiB,CodeCacheKiB:$codeCacheKiB,DataAccessible:$accessible,PersistentDataKiB:(if $dataKiB==null then null else ([0,$dataKiB-($cacheKiB//0)-($codeCacheKiB//0)]|max) end)}' >>"$tmp"
done
manufacturer="$(archphene_adb_run shell getprop ro.product.manufacturer | tr -d '\r')"; model="$(archphene_adb_run shell getprop ro.product.model | tr -d '\r')"; release="$(archphene_adb_run shell getprop ro.build.version.release | tr -d '\r')"; device_abi="$(archphene_adb_run shell getprop ro.product.cpu.abi | tr -d '\r')"; page_size="$(archphene_adb_run shell getconf PAGESIZE | tr -d '\r')"
python3 - "$tmp" "$serial" "$manufacturer" "$model" "$release" "$device_abi" "$page_size" "$output_json" "$output_markdown" "${labels[@]}" <<'PY'
import datetime,json,pathlib,sys
src,serial,maker,model,release,abi,page,out_json,out_md,*labels=sys.argv[1:]; labels=dict(x.split('=',1) for x in labels); rows=[json.loads(x) for x in pathlib.Path(src).read_text().splitlines()]
for r in rows:r['Label']=labels.get(r['Package'],{'org.archpheneos.manager':'Archphene','org.archpheneos.terminal':'Archphene Terminal'}.get(r['Package'],r['Package']))
report={'Schema':'org.archphene.storage-report.v1','CapturedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'Serial':serial,'Manufacturer':maker,'Model':model,'AndroidRelease':release,'DeviceAbi':abi,'PageSize':int(page),'Packages':rows,'ManagerBreakdownKiB':{}}
if out_json:p=pathlib.Path(out_json).resolve();p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(report,indent=2)+'\n')
def mib(v,bytes_=False):return 'n/a' if v is None else f'{v/(1048576 if bytes_ else 1024):.1f}'
if out_md:
 p=pathlib.Path(out_md).resolve();p.parent.mkdir(parents=True,exist_ok=True); lines=['# Archphene Android storage report','',f'Captured: {report["CapturedAtUtc"]}','',f'Device: {maker} {model}; Android {release}; {abi}; {page}-byte pages','','This is a device snapshot. Publish release costs only from a documented clean install and workload.','','| Component | Kind | Version | APK MiB | Installed code MiB | Persistent data MiB | Runtime cache MiB |','| --- | --- | --- | ---: | ---: | ---: | ---: |']
 for r in rows:lines.append(f'| {r["Label"]} | {r["Kind"]} | {r["VersionName"]} | {mib(r["ApkBytes"],True)} | {mib(r["CodeKiB"])} | {mib(r["PersistentDataKiB"])} | {mib(r["CacheKiB"])} |')
 p.write_text('\n'.join(lines)+'\n')
for r in rows:print(f'{r["Label"]:28} {r["Kind"]:18} {r["VersionName"]:12} APK={mib(r["ApkBytes"],True):>6} MiB code={mib(r["CodeKiB"]):>6} MiB persistent={mib(r["PersistentDataKiB"]):>6} MiB cache={mib(r["CacheKiB"]):>6} MiB')
PY
