#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/lib/android-test.sh"

serial=emulator-5554
package=org.archphene.linux.p73ccc00a787cdc19febdd4a01d4b9d10
while (($#)); do
  case "$1" in
    --serial) serial="${2:?}"; shift 2 ;;
    --package) package="${2:?}"; shift 2 ;;
    *) archphene_die "unknown argument: $1" ;;
  esac
done

archphene_test_init "$serial"
archphene_adb_run shell pm path "$package" >/dev/null \
  || archphene_die "Foot wrapper is not installed: $package"
activity="$(archphene_launcher "$package")"
user=files/linux-home/.config/foot/foot.ini
legacy=files/linux-home/.config/foot/.archphene-generated-foot.ini

read_file_base64() {
  archphene_adb_run exec-out run-as "$package" base64 "$1" 2>/dev/null \
    | tr -d '\r\n'
}
write_file_base64() {
  local path="$1" encoded="$2"
  archphene_adb_run shell run-as "$package" sh -c \
    "'mkdir -p files/linux-home/.config/foot; printf %s $encoded | base64 -d > $path'"
}
remove_file() {
  archphene_adb_run shell run-as "$package" rm -f "$1"
}

user_existed=false
legacy_existed=false
original_user=
original_legacy=
if archphene_adb_run shell run-as "$package" test -f "$user"; then
  user_existed=true
  original_user="$(read_file_base64 "$user")"
fi
if archphene_adb_run shell run-as "$package" test -f "$legacy"; then
  legacy_existed=true
  original_legacy="$(read_file_base64 "$legacy")"
fi
cleanup() {
  archphene_adb_run shell am force-stop "$package" >/dev/null 2>&1 || true
  if [[ "$user_existed" == true ]]; then
    write_file_base64 "$user" "$original_user" >/dev/null 2>&1 || true
  else
    remove_file "$user" >/dev/null 2>&1 || true
  fi
  if [[ "$legacy_existed" == true ]]; then
    write_file_base64 "$legacy" "$original_legacy" >/dev/null 2>&1 || true
  else
    remove_file "$legacy" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

legacy_text='# Generated by Archphene from Appearance settings.
[main]
font=monospace:pixelsize=20
pad=8x8
resize-by-cells=no
'
legacy_base64="$(printf %s "$legacy_text" | base64 -w0)"
write_file_base64 "$user" "$legacy_base64"
write_file_base64 "$legacy" "$legacy_base64"
archphene_adb_run shell am force-stop "$package"
archphene_adb_run logcat -c
archphene_adb_run shell am start -W -n "$activity" >/dev/null
log="$(archphene_wait_log \
  'Migrated unmodified legacy Foot appearance configuration' 30 \
  'ArchpheneLinuxApp:I AndroidRuntime:E *:S')"
[[ "$log" != *'FATAL EXCEPTION'* ]] || archphene_die 'Foot crashed during legacy migration'
migrated="$(archphene_adb_run shell run-as "$package" cat "$user")"
[[ "$migrated" == *'# Archphene-managed defaults'* \
    && "$migrated" == *'include='*'/files/linux-home/.config/archphene/foot.ini'* ]] \
  || archphene_die 'exact legacy Foot config did not migrate to managed defaults'

edited_text="${legacy_text}# user-edited legacy config must survive
"
edited_base64="$(printf %s "$edited_text" | base64 -w0)"
write_file_base64 "$legacy" "$legacy_base64"
write_file_base64 "$user" "$edited_base64"
archphene_adb_run shell am force-stop "$package"
archphene_adb_run logcat -c
archphene_adb_run shell am start -W -n "$activity" >/dev/null
archphene_wait_log 'mapped=true.*primary=true.*title=foot' 45 \
  'ArchpheneInput:V ArchpheneLinuxApp:V AndroidRuntime:E *:S' >/dev/null
preserved_base64="$(read_file_base64 "$user")"
[[ "$preserved_base64" == "$edited_base64" ]] \
  || archphene_die 'user-edited legacy Foot config was overwritten'
log="$(archphene_adb_run logcat -d -v brief \
  -s ArchpheneLinuxApp:I AndroidRuntime:E '*:S')"
[[ "$log" != *'Migrated unmodified legacy Foot appearance configuration'* ]] \
  || archphene_die 'edited legacy Foot config was incorrectly reported as migrated'
[[ "$log" != *'FATAL EXCEPTION'* ]] || archphene_die 'Foot crashed with preserved user config'

archphene_note "Foot legacy-config migration passed on $serial: exact generated state migrated; edited user state preserved."
