#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"
serial=emulator-5554; while (($#)); do case "$1" in --serial) serial="${2:?}"; shift 2;; -h|--help) echo "usage: $0 [--serial SERIAL]"; exit 0;; *) archphene_die "unknown argument: $1";; esac; done
archphene_init_adb "$serial"; package=org.archpheneos.manager; archphene_adb_run shell am force-stop "$package"; archphene_adb_run shell am start -W -n "$package/.MainActivity" >/dev/null
archphene_wait_ui 'text="KCalc"' version-home; ui="$ARCHPHENE_UI"; archphene_tap_ui_pattern "$ui" 'text="KCalc"' 'KCalc detail'; archphene_wait_ui 'content-desc="Version selector, 4 versions"' version-detail 20; ui="$ARCHPHENE_UI"
if archphene_regex_contains "$ui" 'text="Pin selected version"[^>]*checked="true"'; then archphene_tap_ui_pattern "$ui" 'text="Pin selected version"[^>]*checked="true"' 'checked pin'; archphene_wait_ui 'text="Pin selected version"[^>]*checked="false"' version-unpinned; ui="$ARCHPHENE_UI"; fi
archphene_tap_ui_pattern "$ui" 'text="Check for update"' 'check for update'; archphene_wait_ui 'content-desc="Version selector, 4 versions"' version-after-check 20; ui="$ARCHPHENE_UI"; archphene_tap_ui_pattern "$ui" 'content-desc="Version selector, 4 versions"' 'version selector'; archphene_wait_ui 'text="26\.04\.0-1"' version-options 20; ui="$ARCHPHENE_UI"; archphene_tap_ui_pattern "$ui" 'text="26\.04\.0-1"' 'archived version'; archphene_wait_ui 'text="Archived version; compatibility not verified"' version-selected; ui="$ARCHPHENE_UI"; archphene_tap_ui_pattern "$ui" 'text="Pin selected version"' 'pin selected version'; archphene_tap_ui_pattern "$ui" 'text="Apps"' 'back to apps'; archphene_wait_ui 'content-desc="Pinned to 26\.04\.0-1\. glibc-x86_64[^"]*"' version-pinned-list; ui="$ARCHPHENE_UI"; archphene_tap_ui_pattern "$ui" 'text="KCalc"' 'pinned KCalc'; archphene_wait_ui 'content-desc="26\.04\.3-1, newer version available"' newer-version-indicator; ui="$ARCHPHENE_UI"; archphene_regex_contains "$ui" 'text="Pin selected version"[^>]*checked="true"' || archphene_die "pin switch not enabled"; archphene_tap_ui_pattern "$ui" 'text="Pin selected version"[^>]*checked="true"' 'enabled pin switch'; archphene_note "Version selector passed: pin icon shown and newer version remains selectable."

