#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"
serial=emulator-5554; query=glmark2-es2-wayland; expected_package=glmark2; expected_file=usr/bin/glmark2-es2-wayland
while (($#)); do case "$1" in --serial) serial="${2:?}"; shift 2;; --query) query="${2:?}"; shift 2;; --expected-package) expected_package="${2:?}"; shift 2;; --expected-file) expected_file="${2:-}"; shift 2;; -h|--help) echo "usage: $0 [options]"; exit 0;; *) archphene_die "unknown argument: $1";; esac; done
archphene_init_adb "$serial"; package=org.archpheneos.manager; archphene_adb_run shell am force-stop "$package"; archphene_adb_run shell am start -W -n "$package/.MainActivity" >/dev/null; archphene_wait_ui 'content-desc="Add Linux app"' ranking-home; ui="$ARCHPHENE_UI"; archphene_tap_ui_pattern "$ui" 'content-desc="Add Linux app"' Add; archphene_wait_ui 'text="Search official Arch packages"' ranking-add; ui="$ARCHPHENE_UI"; archphene_tap_ui_pattern "$ui" 'text="Search official Arch packages"' search-field; archphene_adb_run shell input text "$query"; ui="$(archphene_capture_ui ranking-query)"; archphene_tap_ui_pattern "$ui" 'content-desc="Search package repositories"' search-button
escaped="$(python3 -c 'import re,sys; print(re.escape(sys.argv[1]))' "$expected_package")"; archphene_wait_ui "text=\"$escaped  [^\"]+\"" ranking-results 60; ui="$ARCHPHENE_UI"
if [[ -n "$expected_file" ]]; then expected="Matched file: /$expected_file"; [[ "$ui" == *"text=\"$expected\""* ]] || archphene_die "expected executable match was not shown"; fi
python3 -c 'import sys; package=sys.argv[1].lower(); text=sys.stdin.read().lower(); raise SystemExit(0 if text.find(f"text=\"{package}  ") >= 0 else 1)' "$expected_package" <<<"$ui" || archphene_die "$expected_package was not first ranked result"
archphene_tap_ui_pattern "$ui" 'text="Apps"' Apps; archphene_wait_ui 'text="Search apps"' ranking-apps; ui="$ARCHPHENE_UI"; archphene_tap_ui_pattern "$ui" 'text="Search apps"' app-search; archphene_adb_run shell input text 'extra%smousepad'; archphene_wait_ui 'text="Mousepad"' ranking-installed; ui="$ARCHPHENE_UI"; [[ "$ui" != *'text="KCalc"'* ]] || archphene_die "multi-term search retained unrelated app"; archphene_note "Repository executable discovery and shared search ranking passed."
