#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"
serial=emulator-5554; candidate="$ARCHPHENE_ROOT/tooling/build/manager-self-update/manager-0.9.0.apk"
while (($#)); do case "$1" in --serial) serial="${2:?}"; shift 2;; --candidate-apk) candidate="${2:?}"; shift 2;; -h|--help) echo "usage: $0 [--serial SERIAL] [--candidate-apk PATH]"; exit 0;; *) archphene_die "unknown argument: $1";; esac; done
candidate="$(realpath "$candidate")"; archphene_init_adb "$serial"; package=org.archpheneos.manager; remote=/data/local/tmp/archphene-rejected-update.apk; private="/data/user/0/$package/cache/archphene-rejected-update.apk"
package_version() { local dump code name; dump="$(archphene_adb_run shell dumpsys package "$package")"; code="$(sed -n 's/.*versionCode=\([0-9]*\).*/\1/p' <<<"$dump" | head -n1)"; name="$(sed -n 's/.*versionName=\([^[:space:]]*\).*/\1/p' <<<"$dump" | head -n1)"; [[ -n "$code" && -n "$name" ]] || archphene_die "manager not installed"; printf '%s|%s\n' "$code" "$name"; }
wait_banner() { local expected="$1" deadline=$((SECONDS+15)) ui; while ((SECONDS<deadline)); do sleep 0.5; ui="$(archphene_capture_ui archphene-rejection 2>/dev/null || true)"; [[ "$ui" == *"$expected"* ]] && return; done; archphene_die "did not observe rejection: $expected"; }
rejected_update() { local hash="$1" expected="$2" resumed; archphene_adb_run shell am force-stop "$package"; archphene_adb_run shell am start -W -n "$package/.MainActivity" --es archphene_test_apk_url "file://$private" --es archphene_test_apk_sha256 "$hash" --es archphene_test_apk_package "$package" >/dev/null; wait_banner "$expected"; resumed="$(archphene_adb_run shell dumpsys activity activities)"; ! archphene_regex_contains "$resumed" 'com\.android\.(packageinstaller|permissioncontroller)' || archphene_die "rejected update opened installer"; }
before="$(package_version)"; archphene_adb_run push "$candidate" "$remote" >/dev/null; archphene_adb_run shell run-as "$package" cp "$remote" cache/archphene-rejected-update.apk; archphene_adb_run shell run-as "$package" chmod 600 cache/archphene-rejected-update.apk; hash="$(archphene_sha256_file "$candidate")"; rejected_update "$hash" 'Install failed: APK version downgrade rejected'; [[ "$(package_version)" == "$before" ]] || archphene_die "downgrade changed version"; bad_hash="$(printf '0%.0s' {1..64})"; [[ "$bad_hash" != "$hash" ]] || bad_hash="$(printf 'f%.0s' {1..64})"; rejected_update "$bad_hash" 'Install failed: APK SHA-256 mismatch'; [[ "$(package_version)" == "$before" ]] || archphene_die "checksum rejection changed version"; archphene_note "Manager update rejections passed on $serial: retained $before."
